alias ts="tig status"
alias history="git-file-history"
alias review="gh search prs --review-requested=@me --state=open"
alias recent="git log --oneline -30 | fzf"
alias g="git branch | fzf| xargs git checkout"
alias aliases="bat $ZSH_CUSTOM/aliases.zsh"
alias editaliases="nvim $ZSH_CUSTOM/aliases.zsh"
alias cat="bat"
alias ls="exa"
alias get-process-id="sudo lsof -i" # Add :portNumber
alias kill-process="kill -9" # Add PID
alias n="fd --hidden --type f --exclude .git | fzf --preview 'bat --theme=Dracula --style=numbers --color=always --line-range :500 {}' | xargs nvim"
alias config="nvim ~/.config/nvim/init.vim"
alias test="npm --prefix PATH run test:unit"
alias email="open https://mail.google.com/mail/u/0/#inbox && open https://mail.google.com/mail/u/1/#inbox && open https://mail.google.com/mail/u/2/#inbox"
alias breakdown="docker stop ***************"
alias dev="npm run dev"
alias pr="gh pr view --web"
alias lg="lazygit"
alias update="source ~/.oh-my-zsh/custom/aliases.zsh"