local dap = require('dap')

-- Example config
-- dap.configurations.cs = {
--   {
--     type = "coreclr",
--     name = "launch - netcoredbg",
--     request = "launch",
--     program = function()
--         return vim.fn.input('Path to dll', vim.fn.getcwd() .. '/bin/Debug/', 'file')
--     end,
--   },
-- }

-- Will have to configure this
-- {
--     "version": "0.2.0",
--     "configurations": [
--         {
--             "name": "Launch Web Purchasing (Development)",
--             "type": "coreclr",
--             "request": "launch",
--             "preLaunchTask": "build-wp",
--             "program": "${workspaceFolder}/../WebPurchasing/bin/Debug/net6.0/WebPurchasing.dll",
--             "args": [],
--             "cwd": "${workspaceFolder}/../WebPurchasing",
--             "stopAtEntry": false,
--             "launchBrowser": {
--                 "enabled": false
--             },
--             "env": {
--                 "ASPNETCORE_ENVIRONMENT": "Development",
--                 "DEV_APP_SETTINGS_NAME": "Development"
--             },
--             "sourceFileMap": {
--                 "/Views": "${workspaceFolder}/../WebPurchasing/Views"
--             },
--             "requireExactSource": false,
--             "launchSettingsProfile": "WebPurchasingMac"
--         },
--         {
--             "name": ".NET Core Launch (console)",
--             "type": "coreclr",
--             "request": "launch",
--             "preLaunchTask": "build-email",
--             "program": "${workspaceFolder}/../EmailQueueSenderApplication/bin/Debug/net6.0/EmailQueueSenderApplication.dll",
--             "args": [],
--             "cwd": "${workspaceFolder}/../EmailQueueSenderApplication",
--             "console": "internalConsole",
--             "stopAtEntry": false,
--             "env": {
--                 "APPSETTING_Environment": "Development"
--             }
--         }
--     ]
-- }


-- Will have to configure part of this
-- {
--     "version": "2.0.0",
--     "tasks": [
--         {
--             "label": "build-wp",
--             "command": "dotnet",
--             "type": "process",
--             "args": [
--                 "build",
--                 "${workspaceFolder}/../WebPurchasing/WebPurchasing.csproj",
--                 "/property:GenerateFullPaths=true",
--                 "/consoleloggerparameters:NoSummary"
--             ],
--             "problemMatcher": "$msCompile",
--             "dependsOn": ["gulp-sass", "gulp-sass-content"]
--         },
--         {
--             "label": "gulp-sass",
--             "command": "gulp sass",
--             "type": "shell",
--             "options": {
--                 "cwd": "${workspaceFolder}/../WebPurchasing"
--             },
--         },
--         {
--             "label": "gulp-sass-content",
--             "command": "gulp sass",
--             "type": "shell",
--             "options": {
--                 "cwd": "${workspaceFolder}/../WebPurchasing/Content"
--             },
--         }
--     ]
-- }


-- Doubt I have to configure this
-- dap.adapters.coreclr = {
--   type = 'executable',
--   command = '/usr/local/bin/netcoredbg/netcoredbg',
--   args = {'--interpreter=vscode'}
-- }

